### ISSUE TITLE
Release for Mill 0.11

### ISSUE THREAD

**Issue by alexarchambault** [nafg/mill-bundler#32]
Is there anything that blocks cutting a new release so that Mill 0.11 is supported?

**Comment by nafg** [comment]
Not that I recall. It seems `master` is on 0.11.x so it presumably builds fine with it already.

If you haven't already can you try it with a publish local to make sure there aren't any changes you'd want to get into the release?

**Comment by dthoma** [comment]
I've been using master with webpack and rollup for an app on 0.11. And it works fine so far.

**Comment by nafg** [comment]
Great! I didn't know I even had users ;)

**Comment by nafg** [comment]
I tried to release it but the windows job fails. https://github.com/nafg/mill-bundler/actions/runs/7602916602/job/20704019068

Anyone able to look into it?

**Comment by nafg** [comment]
The error seems to be this:

```
[#1] main.test.ivyJsDeps java.nio.file.AccessDeniedException: C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-library_2.13\1.10.1\.scalajs-library_2.13-1.10.1.jar__sha1.computed12993824255704690508.tmp -> C:\Users\runneradmin\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-library_2.13\1.10.1\.scalajs-library_2.13-1.10.1.jar__sha1.computed
```

**Comment by nafg** [comment]
hmm clearing the cache seems to have fixed it. Maybe the OS should be in the coursier cache key?

**Comment by nafg** [comment]
Ok, 0.2.0 is on Maven Central (or it will be after whatever the delay is)!

**Comment by nafg** [comment]
It shows up now under https://repo1.maven.org/maven2/io/github/nafg/millbundler/

**Comment by dthoma** [comment]
Works just fine, thanks.
Really think that should be integrated into mill at some point as without it scalajs with mill is pretty limited.

**Comment by nafg** [comment]
I'm definitely in that camp, but apparently a lot of people are just fine managing their `package.json` and bundlers by hand, like JS devs do.
